### ISSUE TITLE
The config-options.build2 arrangement will stop working in build2 0.15.0

### ISSUE THREAD

**Issue by boris-kolpackov** [Klaim/fmt-build2#2]
This package shares `config` directives between the library and tests by factoring them into the common `config-options.build2` file. This will stop working without extra arrangements once 0.15.0 is released. For background and what those extra arrangements would be, see: https://build2.org/stage/bpkg/doc/build2-package-manager-manual.xhtml#package-skeleton

However, in this particular case, the better solution is to not have configuration in the tests at all and instead convey it from the library using metadata, as described here: https://github.com/build2/HOWTO/blob/master/entries/convey-additional-information-with-exe-lib.md

**Comment by Klaim** [comment]
Thanks for reminding me, I intend to fix this while working on `v9.0.0`. I suppose I should also revise the other published versions that used the config options.

**Comment by boris-kolpackov** [comment]
> I suppose I should also revise the other published versions that used the config options.

I don't think this is urgent: the existing package archives will still work as long as nobody tries to configure them as dependencies. Which I think is highly unlikely to happen in this case (the only configuration variable it has is to enable modules support which I don't believe works correctly).

**Comment by Klaim** [comment]
Looks like this was closed automatically, but the merged PR didn't fix that.

This issue should be fixed (following @boris-kolpackov 's recommendations) by bef2ed58944c912b993ae46e3b84d8673f9df12c and 56c3e8dbc3694803ca30939b031dad05f7ae3772 .
